spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:note
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
    path: /h2-console

  sql:
    init:
      mode: ALWAYS

logging:
  level:
    org.hibernate.SQL: debug
    com.portfolio.notepad: debug

